<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HPCL202004024deMacBook-Pro.local" name="bigBoyTestReport" tests="93" failures="10" timestamp="2 Sep 2021 08:13:59 GMT" time="47.752" errors="0">
  <testcase name="queryLastInfoTest" time="1.749" classname="bigBoy.app.homepage.appVersionTest"/>
  <testcase name="queryLastInfoTest" time="0.085" classname="bigBoy.app.homepage.lastInfo"/>
  <testcase name="queryHomePageTopTest" time="0.096" classname="bigBoy.app.homepage.homePageTest"/>
  <testcase name="queryHomePageThreadListTest" time="0.865" classname="bigBoy.app.homepage.homePageTest"/>
  <testcase name="queryNewsTest" time="0.342" classname="bigBoy.app.homepage.homePageTest"/>
  <testcase name="sendSecurityCodeTest" time="0.395" classname="bigBoy.app.user.loginTest"/>
  <testcase name="addBigBoyThreadInfoTest" time="2.867" classname="bigBoy.app.bbs.bbsTest"/>
  <testcase name="addBigBoyReplyInfoTest" time="0.001" classname="bigBoy.app.bbs.bbsTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at bigBoy.app.bbs.bbsTest.addBigBoyReplyInfoTest(bbsTest.java:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- addBigBoyReplyInfoTest -->
  <testcase name="queryThreadInfoTest" time="0.321" classname="bigBoy.app.bbs.bbsTest"/>
  <testcase name="queryReplyListTest" time="0.073" classname="bigBoy.app.bbs.bbsTest"/>
  <testcase name="queryAppTradeShowListTest" time="0.154" classname="bigBoy.app.bbs.tradeShowTest"/>
  <testcase name="queryDisplayWindowDetailTest" time="0.069" classname="bigBoy.app.bbs.tradeShowTest">
    <failure type="java.lang.AssertionError" message="expected [SUCCESS] but found [ALERT_MESSAGE]">
      <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [ALERT_MESSAGE]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at bigBoy.app.bbs.tradeShowTest.queryDisplayWindowDetailTest(tradeShowTest.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- queryDisplayWindowDetailTest -->
  <testcase name="addInformChannelTest" time="0.355" classname="bigBoy.app.user.infromTest"/>
  <testcase name="addInformThreadTest" time="0.106" classname="bigBoy.app.user.infromTest"/>
  <testcase name="addInformReplyTest" time="0.08" classname="bigBoy.app.user.infromTest"/>
  <testcase name="queryUserCenterListTest" time="0.182" classname="bigBoy.app.user.userCenter"/>
  <testcase name="getAllMenuGoodsTest" time="0.114" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getAllMenuGoodsTest" time="0.077" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getAllMenuGoodsTest" time="0.11" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getAllMenuGoodsTest" time="0.1" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getAllMenuGoodsTest" time="0.067" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getChannelInfoTest" time="0.276" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getCollectionInfoTest" time="0.086" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getCollectionInfoTest" time="0.056" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getCollectionInfoTest" time="0.066" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getCommentsByChannelTest" time="0.32" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getFlowTest" time="2.48" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getGoodsByCollectionTest" time="5.831" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getRecommendListTest" time="0.351" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getRecommendListTest" time="0.217" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getRecommendListTest" time="0.298" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getRecommendListTest" time="0.172" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="getRecommendListTest" time="0.16" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="hotSearchKeywordsTest" time="0.072" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="searchByKeywordsTest" time="13.269" classname="bigBoy.app.goods.goodsTest"/>
  <testcase name="queryGoodsShopViewById" time="0.27" classname="bigBoy.app.goods.goodsDetailsTest"/>
  <testcase name="getgoodsCommentsTest" time="0.064" classname="bigBoy.app.goods.goodsDetailsTest"/>
  <testcase name="associateThreadTest" time="0.085" classname="bigBoy.app.goods.goodsDetailsTest"/>
  <testcase name="timelineTest" time="0.358" classname="bigBoy.app.goods.timelineTest"/>
  <testcase name="addLotter" time="0.86" classname="bigBoy.app.lottery.lotteryTest"/>
  <testcase name="listTest" time="0.101" classname="bigBoy.app.lottery.lotteryTest"/>
  <testcase name="infoTest" time="0.113" classname="bigBoy.app.lottery.lotteryTest">
    <failure type="java.lang.AssertionError" message="expected [SUCCESS] but found [FAIL]">
      <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [FAIL]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at bigBoy.app.lottery.lotteryTest.infoTest(lotteryTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- infoTest -->
  <testcase name="drawTest" time="0.059" classname="bigBoy.app.lottery.lotteryTest">
    <failure type="java.lang.AssertionError" message="expected [SUCCESS] but found [USER_NOT_FOUND]">
      <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [USER_NOT_FOUND]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at bigBoy.app.lottery.lotteryTest.drawTest(lotteryTest.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- drawTest -->
  <testcase name="shareTest" time="0.06" classname="bigBoy.app.lottery.lotteryTest">
    <failure type="java.lang.AssertionError" message="expected [SUCCESS] but found [USER_NOT_FOUND]">
      <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [USER_NOT_FOUND]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at bigBoy.app.lottery.lotteryTest.shareTest(lotteryTest.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- shareTest -->
  <testcase name="queryAllTest" time="0.068" classname="bigBoy.app.lottery.lotteryTest"/>
  <testcase name="queryAllTest" time="0.058" classname="bigBoy.app.lottery.lotteryTest"/>
  <testcase name="addAddressTest" time="0.061" classname="bigBoy.app.order.receiveAddressTest">
    <failure type="java.lang.AssertionError" message="expected [SUCCESS] but found [DISABLED_LOGIN]">
      <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [DISABLED_LOGIN]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at bigBoy.app.order.receiveAddressTest.addAddressTest(receiveAddressTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- addAddressTest -->
  <testcase name="updateAddressTest" time="0.051" classname="bigBoy.app.order.receiveAddressTest">
    <failure type="java.lang.AssertionError" message="expected [SUCCESS] but found [DISABLED_LOGIN]">
      <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [DISABLED_LOGIN]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at bigBoy.app.order.receiveAddressTest.updateAddressTest(receiveAddressTest.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- updateAddressTest -->
  <testcase name="queryListTest" time="0.05" classname="bigBoy.app.order.receiveAddressTest">
    <failure type="java.lang.AssertionError" message="expected [SUCCESS] but found [DISABLED_LOGIN]">
      <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [DISABLED_LOGIN]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at bigBoy.app.order.receiveAddressTest.queryListTest(receiveAddressTest.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- queryListTest -->
  <testcase name="addCarouseTest" time="0.183" classname="bigBoy.backendapi.homepage.carouseImgTest"/>
  <testcase name="updateCarouseTest" time="0.245" classname="bigBoy.backendapi.homepage.carouseImgTest"/>
  <testcase name="queryCarouseListTest" time="0.033" classname="bigBoy.backendapi.homepage.carouseImgTest"/>
  <testcase name="queryTopInfoTest" time="0.095" classname="bigBoy.backendapi.homepage.carouseImgTest"/>
  <testcase name="deleteCarouseTest" time="0.066" classname="bigBoy.backendapi.homepage.carouseImgTest"/>
  <testcase name="addHotGoodsTest" time="0.182" classname="bigBoy.backendapi.homepage.hotGoodsTest"/>
  <testcase name="updateHotGoodsTest" time="0.352" classname="bigBoy.backendapi.homepage.hotGoodsTest"/>
  <testcase name="updateHotGoodsTest" time="0.376" classname="bigBoy.backendapi.homepage.hotGoodsTest"/>
  <testcase name="updateHotGoodsTest" time="0.223" classname="bigBoy.backendapi.homepage.hotGoodsTest"/>
  <testcase name="queryHotGoodsListTest" time="0.029" classname="bigBoy.backendapi.homepage.hotGoodsTest"/>
  <testcase name="deleteHotGoodsTest" time="0.055" classname="bigBoy.backendapi.homepage.hotGoodsTest"/>
  <testcase name="associateTest" time="0.236" classname="bigBoy.backendapi.goods.goodsAssociateTest"/>
  <testcase name="associateTest" time="0.001" classname="bigBoy.backendapi.goods.goodsAssociateTest">
    <failure type="java.lang.IllegalArgumentException" message="argument type mismatch">
      <![CDATA[java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- associateTest -->
  <testcase name="addShowTest" time="0.158" classname="bigBoy.backendapi.homepage.showTest"/>
  <testcase name="showQueryInfoTest" time="0.04" classname="bigBoy.backendapi.homepage.showTest"/>
  <testcase name="updateShowTest" time="0.06" classname="bigBoy.backendapi.homepage.showTest"/>
  <testcase name="adddisplayWindowTest" time="0.188" classname="bigBoy.backendapi.homepage.showTest"/>
  <testcase name="updatedisplayWindowTest" time="0.086" classname="bigBoy.backendapi.homepage.showTest"/>
  <testcase name="addAssociateTest" time="0.128" classname="bigBoy.backendapi.homepage.showTest"/>
  <testcase name="deleteAssociateTest" time="0.045" classname="bigBoy.backendapi.homepage.showTest"/>
  <testcase name="queryAssociateList" time="0.099" classname="bigBoy.backendapi.homepage.showTest"/>
  <testcase name="deletedisplayWindowTest" time="0.066" classname="bigBoy.backendapi.homepage.showTest"/>
  <testcase name="deleteShowTest" time="0.058" classname="bigBoy.backendapi.homepage.showTest"/>
  <testcase name="queryGoodsInfoByIdTest" time="0.052" classname="bigBoy.backendapi.goods.goodsTest"/>
  <testcase name="searchGoodsTest" time="0.132" classname="bigBoy.backendapi.goods.goodsTest"/>
  <testcase name="searchByCategoryTest" time="0.139" classname="bigBoy.backendapi.goods.goodsTest"/>
  <testcase name="searchGoodsByFactoryIdTest" time="0.427" classname="bigBoy.backendapi.goods.goodsTest"/>
  <testcase name="updateSeriesTest" time="0.153" classname="bigBoy.backendapi.goods.goodsTest"/>
  <testcase name="updateGoodsInfo" time="0.98" classname="bigBoy.backendapi.goods.goodsTest"/>
  <testcase name="updateGoodsPics" time="0.259" classname="bigBoy.backendapi.goods.goodsTest"/>
  <testcase name="updateGoodsStatus" time="0.121" classname="bigBoy.backendapi.goods.goodsTest"/>
  <testcase name="goodsCommentsOnlineTest" time="0.078" classname="bigBoy.backendapi.goods.goodsTest"/>
  <testcase name="addChannelTest" time="0.327" classname="bigBoy.backendapi.goods.goodsTest">
    <failure type="java.lang.AssertionError" message="expected [SUCCESS] but found [FAIL]">
      <![CDATA[java.lang.AssertionError: expected [SUCCESS] but found [FAIL]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at bigBoy.backendapi.goods.goodsTest.addChannelTest(goodsTest.java:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- addChannelTest -->
  <testcase name="collectionTest" time="1.814" classname="bigBoy.backendapi.goods.collectionsTest"/>
  <testcase name="collectionTest" time="2.012" classname="bigBoy.backendapi.goods.collectionsTest"/>
  <testcase name="collectionTest" time="1.514" classname="bigBoy.backendapi.goods.collectionsTest"/>
  <testcase name="searchCollection" time="0.048" classname="bigBoy.backendapi.goods.collectionsTest"/>
  <testcase name="searchCollection" time="0.041" classname="bigBoy.backendapi.goods.collectionsTest"/>
  <testcase name="searchCollection" time="0.072" classname="bigBoy.backendapi.goods.collectionsTest"/>
  <testcase name="searchCollection" time="0.034" classname="bigBoy.backendapi.goods.collectionsTest"/>
  <testcase name="addHotSearchKeywordsTest" time="0.252" classname="bigBoy.backendapi.hotSearchKeywordsTest"/>
  <testcase name="updateHotSearchKeywordsTest" time="0.267" classname="bigBoy.backendapi.hotSearchKeywordsTest"/>
  <testcase name="queryHotSearchKeywordsListTest" time="0.029" classname="bigBoy.backendapi.hotSearchKeywordsTest"/>
  <testcase name="deleteHotSearchKeywordsTest" time="0.053" classname="bigBoy.backendapi.hotSearchKeywordsTest"/>
</testsuite> <!-- bigBoyTestReport -->
